apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: application-statefulset-mysql
  namespace: test
spec:
  selector:
    matchLabels:
      app: db
  serviceName: "application-svc-mysql"
  replicas: 2
#  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: haridtvt/app-mysql:v30
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: mysql_root_password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config-map
              key: mysql_database
  volumeClaimTemplates:
  - metadata:
      namespace: test
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "app-sc"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: application-svc-mysql
  labels:
    app: db
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: db
