CREATE TABLE IF NOT EXISTS users(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FULLNAME VARCHAR(100) NOT NULL,
    AGE INT NOT NULL,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(UNIQUE) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);