apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.BackendServiceName" . }}-backend
  labels:
    {{- include "helm.SvcBackendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5001
      protocol: TCP
      name: backend-port
  selector:
        {{- include "helm.BackendLabels" . | nindent 4 }}
