apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-map
  namespace: test
data:
  db_name: "devops_db"
  db_host: "application-svc-mysql.test.svc.cluster.local"
  db_user: "root"
  dns_resolve: "10.96.0.10"
  service_backend: "application-svc-backend.test.svc.cluster.local"
